[workspace]
members = ["packages/*"]

[workspace.package]
description = "Bitcoin ZK client."
cairo-version = "2.8.2"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/keep-starknet-strange/raito"
license-file = "LICENSE"

[workspace.dependencies]
cairo_test = "2.8.0"

[features]
default = ["log_level_none"]
log_level_none = []
log_level_trace = []
log_level_debug = []
