[package]
name = "consensus"
version = "0.1.0"
edition = "2024_07"

[dependencies]
utils = { path = "../utils" }
raito_macros = { path = "../macros" }

[dev-dependencies]
cairo_test.workspace = true

[scripts]
# TODO: cairo lint
lint = "scarb fmt"

[features]
log_level_trace = []
log_level_debug = []