[package]
name = "raito_logging"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[cairo-plugin]


[features]
default = ["log_level_none"]
log_level_none = []
log_level_trace = []
log_level_debug = []
