[package]
name = "logging"
version = "0.1.0"
edition = "2024_07"

[features]
default = ["log_level_none"]
log_level_none = []
log_level_trace = []
log_level_debug = []

[dev-dependencies]
cairo_test.workspace = true
